services:
  api:
    image: ${API_IMAGE:-josefdigital/platform:platform_api-v0.0.3}
    restart: always
    env_file:
      - ${APP_ENV_FILE:-.env}
    volumes:
      - /opt/caddy/data/api-uploads:/server/uploads
    ports:
      - "8001:8001"

  web:
    image: ${WEB_IMAGE:-josefdigital/platform:platform_web-v0.0.3}
    restart: always
    env_file:
      - ${APP_ENV_FILE:-.env}
    volumes:
      - /opt/caddy/data/api-uploads:/server/uploads
    ports:
      - "8000:8000"

  caddy:
    image: caddy:2.6.4
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/caddy/data:/data
      - caddy_config:/config

volumes:
  caddy_config:
