[db]
leadstorefront-db ansible_host=138.68.118.78 ansible_user=root ansible_ssh_private_key_file=~/.ssh/leadstorefront
[app]
leadstorefront-app ansible_host=67.207.68.181 ansible_user=root ansible_ssh_private_key_file=~/.ssh/leadstorefront
